// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core"

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		ContentComp: typeof import("./src/components/ContentComp.vue")["default"]
		Footer: typeof import("./src/components/Footer.vue")["default"]
		FooterComp: typeof import("./src/components/FooterComp.vue")["default"]
		FourBlockComp: typeof import("./src/components/FourBlockComp.vue")["default"]
		"ICarbon:locked": typeof import("~icons/carbon/locked")["default"]
		"ICarbon:user": typeof import("~icons/carbon/user")["default"]
		"IMdi:weatherNight": typeof import("~icons/mdi/weather-night")["default"]
		"IMdi:weatherSunny": typeof import("~icons/mdi/weather-sunny")["default"]
		NavBar: typeof import("./src/components/NavBar.vue")["default"]
		RouterLink: typeof import("vue-router")["RouterLink"]
		RouterView: typeof import("vue-router")["RouterView"]
		SidebarComp: typeof import("./src/components/SidebarComp.vue")["default"]
		TwoBlockComp: typeof import("./src/components/TwoBlockComp.vue")["default"]
	}
}

export {}
