// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core"

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		AdminMgmtHomeComp: typeof import("./src/components/adminMgmtComp/AdminMgmtHomeComp.vue")["default"]
		CommentComp: typeof import("./src/components/CommentComp.vue")["default"]
		ContentComp: typeof import("./src/components/ContentComp.vue")["default"]
		FooterComp: typeof import("./src/components/FooterComp.vue")["default"]
		HomeworkMgmtComp: typeof import("./src/components/adminMgmtComp/HomeworkMgmtComp.vue")["default"]
		"ICarbon:locked": typeof import("~icons/carbon/locked")["default"]
		"ICarbon:user": typeof import("~icons/carbon/user")["default"]
		"IFad:random1dice": typeof import("~icons/fad/random1dice")["default"]
		"IIc:outlineEmail": typeof import("~icons/ic/outline-email")["default"]
		"IIc:twotoneUploadFile": typeof import("~icons/ic/twotone-upload-file")["default"]
		"IMdi:weatherNight": typeof import("~icons/mdi/weather-night")["default"]
		"IMdi:weatherSunny": typeof import("~icons/mdi/weather-sunny")["default"]
		MarkdownComp: typeof import("./src/components/MarkdownComp.vue")["default"]
		MemberMgmtComp: typeof import("./src/components/adminMgmtComp/MemberMgmtComp.vue")["default"]
		NavBar: typeof import("./src/components/NavBar.vue")["default"]
		ResetPasswordComp: typeof import("./src/components/ResetPasswordComp.vue")["default"]
		RouterLink: typeof import("vue-router")["RouterLink"]
		RouterView: typeof import("vue-router")["RouterView"]
		SidebarComp: typeof import("./src/components/SidebarComp.vue")["default"]
		TwoBlockComp: typeof import("./src/components/TwoBlockComp.vue")["default"]
		UserHomeComp: typeof import("./src/components/UserHomeComp.vue")["default"]
		UserInfoComp: typeof import("./src/components/profileComp/userInfoComp.vue")["default"]
		UserResetPWDComp: typeof import("./src/components/profileComp/userResetPWDComp.vue")["default"]
	}
}

export {}
